# Generated by Django 3.2.9 on 2023-12-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_Admin', models.IntegerField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=120, null=True)),
                ('Phone_Admins', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('mail_admins', models.CharField(max_length=120, null=True)),
                ('naznach_Admins', models.DateField(null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id_bar', models.IntegerField(primary_key=True, serialize=False)),
                ('price_bar', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'bar',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('Phone_client', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('username', models.CharField(db_column='username', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id_computers', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20, null=True)),
                ('password', models.IntegerField(null=True)),
                ('device', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'computers',
            },
        ),
        migrations.CreateModel(
            name='Pristavka',
            fields=[
                ('id_pristav', models.IntegerField(primary_key=True, serialize=False)),
                ('nazvanie', models.CharField(max_length=20, null=True)),
                ('price_pristavka', models.IntegerField(null=True)),
                ('game', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'pristavka',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.IntegerField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=120, null=True)),
                ('Phone_Worker', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('mail_worker', models.CharField(max_length=20, null=True)),
                ('naznach_Worker', models.DateField(null=True)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id_rooms', models.IntegerField(primary_key=True, serialize=False)),
                ('vip', models.BooleanField(null=True)),
                ('price_rooms', models.IntegerField(null=True)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='serverrab.client')),
                ('id_computers', models.ForeignKey(db_column='id_computers', on_delete=django.db.models.deletion.CASCADE, to='serverrab.computers')),
                ('id_pristav', models.ForeignKey(db_column='id_pristav', on_delete=django.db.models.deletion.CASCADE, to='serverrab.pristavka')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_orders', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_order', models.DateField(null=True)),
                ('price_time', models.IntegerField(null=True)),
                ('id_Admin', models.ForeignKey(db_column='id_Admin', on_delete=django.db.models.deletion.CASCADE, to='serverrab.admin')),
                ('id_bar', models.ForeignKey(db_column='id_bar', null=True, on_delete=django.db.models.deletion.CASCADE, to='serverrab.bar')),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='serverrab.client')),
                ('id_worker', models.ForeignKey(db_column='id_worker', on_delete=django.db.models.deletion.CASCADE, to='serverrab.worker')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CompClub',
            fields=[
                ('id_compclube', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('id_Admin', models.ForeignKey(db_column='id_Admin', on_delete=django.db.models.deletion.CASCADE, to='serverrab.admin')),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='serverrab.client')),
                ('id_computers', models.ForeignKey(db_column='id_computers', on_delete=django.db.models.deletion.CASCADE, to='serverrab.computers')),
                ('id_orders', models.ForeignKey(db_column='id_orders', on_delete=django.db.models.deletion.CASCADE, to='serverrab.orders')),
                ('id_pristav', models.ForeignKey(db_column='id_pristav', on_delete=django.db.models.deletion.CASCADE, to='serverrab.pristavka')),
                ('id_rooms', models.ForeignKey(db_column='id_rooms', on_delete=django.db.models.deletion.CASCADE, to='serverrab.rooms')),
                ('id_worker', models.ForeignKey(db_column='id_worker', on_delete=django.db.models.deletion.CASCADE, to='serverrab.worker')),
            ],
            options={
                'db_table': 'compclube',
            },
        ),
    ]
