# Generated by Django 5.1.7 on 2025-03-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverrab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='worker',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
